# Generated by Django 5.1.4 on 2025-02-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('netbox_otp_plugin.device',),
        ),
    ]
